//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fleet
    {
        public int FLEETID { get; set; }
        public string FLEETNumber { get; set; }
        public string FLEETName { get; set; }
        public string FLEETDescription { get; set; }
        public string FLEETRego { get; set; }
    }
}
